---
- name: Install and configure Consul
  hosts: nomad
  become: true
  vars:
    nomad_datacenter_name: "dc1"
    nomad_server_bootstrap_expect: 3
    consul_generated_encrypt_key: "REPLACE_ME_WITH_KEY"
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - gnupg
        state: present
      become: true

    - name: Create keyrings directory if it doesn't exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add HashiCorp apt GPG key
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/keyrings/hashicorp.gpg
        mode: '0644'

    - name: Get architecture
      command: dpkg --print-architecture
      register: arch

    - name: Get distro codename
      command: lsb_release -cs
      register: distro

    - name: Add consul user
      user:
        name: consul
        shell: /bin/false
        system: yes

    - name: Create consul group
      group:
        name: consul
        system: yes

    - name: Create consul directories
      file:
        path: '{{ item }}'
        state: directory
        recurse: yes
        owner: consul
        group: consul
        mode: 0750
      loop:
        - /etc/consul.d
        - /opt/consul


    - name: Add HashiCorp APT repository
      copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: |
          deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ distro.stdout }} main
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install or update consul
      apt:
        name: consul
        state: latest
        update_cache: yes
    #
    # - name: Copy consul base configuration
    #   copy:
    #     dest: /etc/consul.d/consul.hcl
    #     content: |
    #       datacenter = "{{ nomad_datacenter_name }}"
    #       data_dir = "/opt/consul"
    #       encrypt = "{{ consul_generated_encrypt_key }}"
    #       verify_incoming = true
    #       verify_outgoing = true
    #       verify_server_hostname = true
    #       bind_addr = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
    #       client_addr = "0.0.0.0"
    #       ca_file = "/etc/consul.d/consul-agent-ca.pem"
    #       cert_file = "/etc/consul.d/{{ nomad_datacenter_name }}-server-consul-0.pem"
    #       key_file = "/etc/consul.d/{{ nomad_datacenter_name }}-server-consul-0-key.pem"
    #       auto_encrypt {
    #         allow_tls = true
    #       }
    #       retry_join = ["{{ groups.nomad|difference([inventory_hostname]) | join('", "')}}"]
    #       acl {
    #         enabled = false
    #         default_policy = "allow"
    #         enable_token_persistence = true
    #       }
    #       performance {
    #         raft_multiplier = 1
    #       }
    #       recursors = ["192.168.0.1"]
    #     owner: consul
    #     group: consul
    #     mode: 0640
    #
    # - name: Copy consul-server configuration
    #   copy:
    #     dest: /etc/consul.d/consul-server.hcl
    #     content: |
    #       server = true
    #       bootstrap_expect = {{ nomad_server_bootstrap_expect }}
    #       connect {
    #         enabled = true
    #       }
    #       addresses {
    #         grpc = "127.0.0.1"
    #       }
    #       ports {
    #         grpc_tls  = 8503
    #       }
    #     owner: consul
    #     group: consul
    #     mode: 0640
    #
    # - name: Copy consul systemd unit file
    #   copy:
    #     dest: /etc/systemd/system/consul.service
    #     content: |
    #       [Unit]
    #       Description="HashiCorp Consul - A service mesh solution"
    #       Documentation=https://www.consul.io/
    #       Requires=network-online.target
    #       After=network-online.target
    #       ConditionFileNotEmpty=/etc/consul.d/consul.hcl
    #       [Service]
    #       EnvironmentFile=-/etc/consul.d/consul.env
    #       User=consul
    #       Group=consul
    #       ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
    #       ExecReload=/bin/kill --signal HUP $MAINPID
    #       KillMode=process
    #       KillSignal=SIGTERM
    #       Restart=on-failure
    #       LimitNOFILE=65536
    #       [Install]
    #       WantedBy=multi-user.target
    #     owner: root
    #     group: root
    #     mode: 0644
    #
    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Enable and start consul
      systemd:
        name: consul
        enabled: yes
        state: started
